name: Laravel CI/CD with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Lấy mã nguồn
      - name: Checkout code
        uses: actions/checkout@v4
      # Cài đặt Docker (nếu chưa có)
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install docker-ce docker-ce-cli containerd.io

      # Cài đặt Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      

      # Thiết lập Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build container cho PHP
      - name: Build PHP container
        run: |
          docker-compose -f docker-compose.yml build

      # Khởi động các dịch vụ Docker (nginx, mysql, redis, app)
      - name: Start Docker containers
        run: |
          docker-compose -f docker-compose.yml up -d

      # Chạy migrate và seed database
      - name: Run database migrations
        run: |
          docker-compose exec app php artisan migrate --force

      # Chạy test Laravel
      - name: Run Tests
        run: |
          docker-compose exec app php artisan test

      # Đóng Docker containers sau khi test xong
      - name: Stop Docker containers
        run: |
          docker-compose down
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Thiết lập SSH Agent và add SSH private key
      - name: Setup SSH for deployment
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Deploy tới server qua SSH
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
          cd /path/to/your/project &&
          git pull origin main &&
          docker-compose down &&
          docker-compose up -d --build &&
          docker-compose exec app php artisan migrate --force"


