name: Laravel CI/CD with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Lấy mã nguồn
      - name: Checkout code
        uses: actions/checkout@v4

      # Thiết lập Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build container cho PHP
      - name: Build PHP container
        run: |
          docker-compose -f docker-compose.yml build

      # Khởi động các dịch vụ Docker (nginx, mysql, redis, app)
      - name: Start Docker containers
        run: |
          docker-compose -f docker-compose.yml up -d

      # Chạy migrate và seed database
      - name: Run database migrations
        run: |
          docker-compose exec app php artisan migrate --force

      # Chạy test Laravel
      - name: Run Tests
        run: |
          docker-compose exec app php artisan test

      # Đóng Docker containers sau khi test xong
      - name: Stop Docker containers
        run: |
          docker-compose down
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
          cd /path/to/your/project &&
          git pull origin main &&
          docker-compose down &&
          docker-compose up -d --build &&
          docker-compose exec app php artisan migrate --force"

